{% set version = "4.0.10" %}

package:
  name: libtiff
  version: {{ version }}

source:
  url: https://download.osgeo.org/libtiff/tiff-{{ version }}.tar.gz
  sha256: 2c52d11ccaf767457db0c46795d9c7d1a8d8f76f68b0b800a3dfe45786b996e4
  patches:
    - patches/0001-CVE-2017-11613_part1.patch
    - patches/0002-CVE-2017-11613_part2.patch
    - patches/fix_TIFFReadRawStrip_man_page_typo.patch
    - patches/fixed_lossless_webp_compression_config.patch

build:
  number: 1002
  # Does a very good job of maintaining compatibility.
  #    https://abi-laboratory.pro/tracker/timeline/libtiff/
  run_exports:
    - {{ pin_subpackage('libtiff', max_pin='x') }}
  missing_dso_whitelist:
    # Only used by libtiff,bin/tiffgt (a viewer), which is ok.
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake   # [win]
    - make    # [not win]
  host:
    - zlib
    - jpeg
    - xz  # [not win]
  run:
    - zlib
    - jpeg
    - xz  # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a                            # [unix]
    - test -f ${PREFIX}/lib/libtiffxx.a                          # [unix]
    - test -f ${PREFIX}/lib/libtiff${SHLIB_EXT}                  # [unix]
    - test -f ${PREFIX}/lib/libtiffxx${SHLIB_EXT}                # [unix]
    - if not exist %PREFIX%\\Library\\bin\\tiff.dll exit 1       # [win]
    - if not exist %PREFIX%\\Library\\bin\\tiffxx.dll exit 1     # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiff.dll exit 1    # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiffxx.dll exit 1  # [win]

about:
  home: http://www.libtiff.org/
  license: HPND
  license_file: COPYRIGHT
  summary: 'Support for the Tag Image File Format (TIFF).'
  description: |
    This software provides support for the Tag Image File Format (TIFF), a
    widely used format for storing image data.
  doc_url: http://www.libtiff.org/document.html

extra:
   recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
