{% set version = "4.0.8" %}

package:
  name: libtiff
  version: {{ version }}

source:
  fn: tiff-{{ version }}.tar.gz
  url: http://download.osgeo.org/libtiff/tiff-{{ version }}.tar.gz
  sha256: 59d7a5a8ccd92059913f246877db95a2918e6c04fb9d43fd74e5c3390dac2910

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - toolchain
    - zlib 1.2.*
    - jpeg 9*
    - xz 5.2.*  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - zlib 1.2.*
    - jpeg 9*
    - xz 5.2.*  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a  # [unix]
    - test -f ${PREFIX}/lib/libtiffxx.a  # [unix]
    - test -f ${PREFIX}/lib/libtiff.so  # [linux]
    - test -f ${PREFIX}/lib/libtiff.dylib  # [osx]
    - test -f ${PREFIX}/lib/libtiffxx.so  # [linux]
    - test -f ${PREFIX}/lib/libtiffxx.dylib  # [osx]
    #- conda inspect linkages -p $PREFIX libtiff  # [not win]
    #- conda inspect objects -p $PREFIX libtiff  # [osx]

about:
  home: http://www.remotesensing.org/libtiff/
  license: HPND
  summary: 'Support for the Tag Image File Format (TIFF).'

extra:
   recipe-maintainers:
    - jakirkham
    - ocefpaf
    - stuarteberg
